ext.versions = [:]
def versions = [:]
versions.compile_sdk = 33
versions.min_sdk = 21
versions.target_sdk = 33
versions.sdk_version_major = '1'
versions.sdk_version_minor = '9'
versions.sdk_version_patch = '1'
versions.sdk_version_code = 14
versions.core = "1.8.0"
versions.appcompat = "1.4.2"
versions.junit = "4.13.2"
versions.android_junit = "1.1.5"
versions.espresso_core = "3.5.1"
versions.retrofit = '2.9.0'
versions.okhttp = '4.9.3'
versions.gson = '2.8.6'
versions.kotlin = '1.6.20'
versions.coroutines = "1.6.4"
versions.sentry = '6.12.1'
versions.dagger = '2.42'
versions.room = '2.4.3'
versions.chucker = '3.5.2'
ext.versions = versions


ext.deps = [:]
def deps = [:]

def internal = [:]
internal.sdk = project(":internalsdk")
deps.internal = internal

def android_core = [:]
android_core.core = "androidx.core:core-ktx:$versions.core"
android_core.appcompat = "androidx.appcompat:appcompat:$versions.appcompat"
deps.android_core = android_core

def kotlin = [:]
kotlin.reflect = "org.jetbrains.kotlin:kotlin-reflect:$versions.kotlin"
kotlin.coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:$versions.coroutines"
kotlin.coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:$versions.coroutines"
kotlin.corountines_test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:$versions.coroutines"
deps.kotlin = kotlin

def dagger = [:]
dagger.main = "com.google.dagger:dagger:$versions.dagger"
dagger.compiler = "com.google.dagger:dagger-compiler:$versions.dagger"
deps.dagger = dagger

def retrofit = [:]
retrofit.main = "com.squareup.retrofit2:retrofit:$versions.retrofit"
retrofit.gson = "com.squareup.retrofit2:converter-gson:$versions.retrofit"
deps.retrofit = retrofit

def okhttp = [:]
okhttp.main = "com.squareup.okhttp3:okhttp:$versions.okhttp"
okhttp.http_interceptor = "com.squareup.okhttp3:logging-interceptor:$versions.okhttp"
deps.okhttp = okhttp

def gson = [:]
gson.main = "com.google.code.gson:gson:$versions.gson"
deps.gson = gson

def sentry = [:]
sentry.main = "io.sentry:sentry-android:$versions.sentry"
sentry.okhttp = "io.sentry:sentry-android-okhttp:$versions.sentry"
deps.sentry = sentry

def testing = [:]
testing.junit = "junit:junit:$versions.junit"
testing.android_junit = "androidx.test.ext:junit:$versions.android_junit"
testing.espresso = "androidx.test.espresso:espresso-core:$versions.espresso_core"
deps.testing = testing

def room= [:]
room.main = "androidx.room:room-runtime:$versions.room"
room.ktx = "androidx.room:room-ktx:$versions.room"
room.compiler = "androidx.room:room-compiler:$versions.room"
deps.room = room

//def chucker = [:]
//chucker.main = "com.github.chuckerteam.chucker:library:$versions.chucker"
//chucker.no_op = "com.github.chuckerteam.chucker:library-no-op:$versions.chucker"
//deps.chucker = chucker

ext.deps = deps
