# Kepping all models
-keep class com.likeminds.likemindsfeed.comment.model.** { *; }
-keep class com.likeminds.likemindsfeed.configuration.model.** { *; }
-keep class com.likeminds.likemindsfeed.helper.model.** { *; }
-keep class com.likeminds.likemindsfeed.user.model.** { *; }
-keep class com.likeminds.likemindsfeed.moderation.model.** { *; }
-keep class com.likeminds.likemindsfeed.notificationfeed.model.** { *; }
-keep class com.likeminds.likemindsfeed.post.model.** { *; }
-keep class com.likeminds.likemindsfeed.sdk.model.** { *; }
-keep class com.likeminds.likemindsfeed.topic.model.** { *; }
-keep class com.likeminds.likemindsfeed.universalfeed.model.** { *; }
-keep class com.likeminds.likemindsfeed.widgets.model.** { *; }