dependencies {
    //android core
    implementation deps.android_core.core
    implementation deps.android_core.appcompat

    //room
    implementation deps.room.main
    kapt deps.room.compiler

    //dagger
    implementation deps.dagger.main
    kapt deps.dagger.compiler

    //network
    implementation deps.retrofit.main
    implementation deps.retrofit.gson
    implementation deps.okhttp.main
    implementation deps.okhttp.http_interceptor
    debugImplementation deps.chucker.main
    releaseImplementation deps.chucker.no_op

    //work manager
    implementation deps.work_manager.main

    //coroutines
    implementation deps.kotlin.coroutines_core

    //sentry
    implementation deps.sentry.main
    implementation deps.sentry.okhttp

    //aws
    implementation deps.aws.s3
    implementation(deps.aws.mobile_client) { transitive = true }

    //testing
    testImplementation deps.testing.junit
    androidTestImplementation deps.testing.android_junit
    androidTestImplementation deps.testing.espresso
}