ext.keys = [:]

def keys = [:]
keys.CARAVAN_BASE_URL = "CARAVAN_BASE_URL"
keys.KETTLE_BASE_URL = "KETTLE_BASE_URL"
keys.DOMAIN = "DOMAIN"
keys.IDENTITY_POOL_ID = "IDENTITY_POOL_ID"
keys.BUCKET_NAME = "BUCKET_NAME"
keys.BUCKET_BASE_URL = "BUCKET_BASE_URL"
keys.SENTRY_DSN = "SENTRY_DSN"
ext.keys = keys

ext.urls = [:]
def urls = [:]
urls."$keys.CARAVAN_BASE_URL" = "\"https://www.likeminds.community/\""
urls."$keys.KETTLE_BASE_URL" = "\"https://auth.likeminds.community/\""
urls."$keys.DOMAIN" = "\"www.likeminds.community\""
urls."$keys.IDENTITY_POOL_ID" = "\"ap-south-1:d73bc2ed-bede-42c8-bab7-0abe0a001325\""
urls."$keys.BUCKET_NAME" = "\"prod-likeminds-media\""
urls."$keys.BUCKET_BASE_URL" = "\"https://prod-likeminds-media.s3.amazonaws.com/\""
urls."$keys.SENTRY_DSN" = "\"https://5802d81a53354c2593a6683813e26f78@o613148.ingest.sentry.io/5748758\""
ext.urls = urls

ext.beta_urls = [:]
def beta_urls = [:]
beta_urls."$keys.CARAVAN_BASE_URL" = "\"https://beta.likeminds.community/\""
beta_urls."$keys.KETTLE_BASE_URL" = "\"https://betaauth.likeminds.community/\""
beta_urls."$keys.DOMAIN" = "\"beta.likeminds.community\""
beta_urls."$keys.IDENTITY_POOL_ID" = "\"ap-south-1:181963ba-f2db-450b-8199-964a941b38c2\""
beta_urls."$keys.BUCKET_NAME" = "\"beta-likeminds-media\""
beta_urls."$keys.BUCKET_BASE_URL" = "\"https://beta-likeminds-media.s3.amazonaws.com/\""
beta_urls."$keys.SENTRY_DSN" = "\"https://5802d81a53354c2593a6683813e26f78@o613148.ingest.sentry.io/5748758\""
ext.beta_urls = beta_urls

dependencies {
    //android core
    implementation deps.android_core.core
    implementation deps.android_core.appcompat

//    room
    implementation deps.room.main
    kapt deps.room.compiler

    //dagger
    implementation deps.dagger.main
    kapt deps.dagger.compiler

    //network
    implementation deps.retrofit.main
    implementation deps.retrofit.gson
    implementation deps.okhttp.main
    implementation deps.okhttp.http_interceptor
    debugImplementation deps.chucker.main
    releaseImplementation deps.chucker.no_op

    //work manager
    implementation deps.work_manager.main

    //coroutines
    implementation deps.kotlin.coroutines_core

    //sentry
    implementation deps.sentry.main
    implementation deps.sentry.okhttp

    //aws
    implementation deps.aws.s3
    implementation(deps.aws.mobile_client) { transitive = true }

    implementation deps.exifinterface.main

    //testing
    testImplementation deps.testing.junit
    androidTestImplementation deps.testing.android_junit
    androidTestImplementation deps.testing.espresso
}